"""initial

Revision ID: 151a2bb86730
Revises: 
Create Date: 2026-06-11 15:33:52.189892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '151a2bb86730'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nationality', sa.String(length=3), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('passport_expiry', sa.String(length=20), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('work_years', sa.Integer(), nullable=True),
    sa.Column('language_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('travel_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subscription_tier', sa.Enum('free', 'pro', 'premium', 'enterprise', name='subscriptiontier'), nullable=False),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('visa_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('visa_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('processing_days_min', sa.Integer(), nullable=False),
    sa.Column('processing_days_max', sa.Integer(), nullable=False),
    sa.Column('fee_usd', sa.Float(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('eligibility_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embassy_url', sa.String(length=500), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_programs_country_code'), 'visa_programs', ['country_code'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('visa_program_id', sa.UUID(), nullable=True),
    sa.Column('destination_country', sa.String(length=3), nullable=True),
    sa.Column('visa_type', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('intended_travel_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('discovery', 'assessment', 'documents', 'form_filling', 'review', 'submitted', 'approved', 'rejected', name='casestatus'), nullable=False),
    sa.Column('readiness_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('eligibility_score', sa.Float(), nullable=True),
    sa.Column('agent_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visa_program_id'], ['visa_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('passport', 'bank_statement', 'employment_letter', 'degree_certificate', 'tax_return', 'invitation_letter', 'language_score_card', 'photo', 'medical_certificate', 'police_clearance', 'travel_insurance', 'admission_letter', 'other', name='documenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('storage_url', sa.String(length=1000), nullable=True),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'validated', 'rejected', 'expired', name='documentstatus'), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_fixes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('personalized_description', sa.String(length=1000), nullable=False),
    sa.Column('requirement_detail', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'validated', 'rejected', 'waived', name='checkliststatus'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_checklists')
    op.drop_table('notifications')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('cases')
    op.drop_index(op.f('ix_visa_programs_country_code'), table_name='visa_programs')
    op.drop_table('visa_programs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
