"""replace_s3_fields_with_drive_fields_in_documents

Revision ID: 845768169568
Revises: 253dbb5bf9b5
Create Date: 2026-06-11 18:51:20.230408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845768169568'
down_revision: Union[str, None] = '253dbb5bf9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('drive_file_id', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('drive_view_link', sa.String(length=1000), nullable=True))
    op.add_column('documents', sa.Column('drive_folder_id', sa.String(length=500), nullable=True))
    op.drop_column('documents', 'storage_key')
    op.drop_column('documents', 'storage_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('storage_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('documents', 'drive_folder_id')
    op.drop_column('documents', 'drive_view_link')
    op.drop_column('documents', 'drive_file_id')
    # ### end Alembic commands ###
